### ISSUE TITLE
Updates to this library

### ISSUE THREAD

**Issue by ericoporto** [encharm/UELinuxNativeDialogs#2]
I noticed there hasn't been a commit here since 2014, are there any updates on maintaining this library? It is a very useful one. It could gain traction by dropping the UE reference since even it being used there, it doesn't appear to require UE to be used elsewhere.

**Comment by Rush** [comment]
Hi @ericoporto - what's your use case? PRs are welcome

**Comment by ericoporto** [comment]
Cool, I will fork and work on a little something later and PR once it's properly working.
